export const TRISSEA_PRIMARY_HEX = '#14622e';
export const TRISSEA_PRIMARY_FOREGROUND_HEX = '#ffffff';
export const TRISSEA_ACCENT_HEX = '#fecc04';
export const TRISSEA_ACCENT_FOREGROUND_HEX = '#0f1f16';
export const TRISSEA_BACKGROUND_HEX = '#f5f9f7';
export const TRISSEA_FOREGROUND_HEX = '#0f1f16';

export const DEFAULT_PRIMARY_HEX = TRISSEA_PRIMARY_HEX;
export const DEFAULT_ACCENT_HEX = TRISSEA_ACCENT_HEX;
export const DEFAULT_BACKGROUND_HEX = TRISSEA_BACKGROUND_HEX;
export const DEFAULT_FOREGROUND_HEX = TRISSEA_FOREGROUND_HEX;
export const PWA_BACKGROUND_HEX = TRISSEA_BACKGROUND_HEX;
